appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: tOEsoatEjfqFKxofYOt6IOr3xTuST+n+jHKPscbriJ2cL3injUScgEojofxYAJPfxr99kObTlsOqzxEy2DyOlu7g1efvQhd/KRl+ykfBb2mQHb+zwsWo1iXWGmyxRuZBxLLpdeduu0JDBhhhdl2y/pw7+LQuMTNkiehOSA4Ue79IZ4GJCzINykdN1tMdiA7rS08/4ZUuPXYV7mSQ2to6hOOZJn31WdNJLSUXwxtUMMA1vTtUcNQa4MYu9fXxOU8eFdgm0GBRHT0t/YWXV8V+EyuPjl0a3HAV6G/rYMkIfYhYrRMtav6rw+YLahc3QPT5WYGyK/qyrW6yOSKzKSDpk16Qg0cbSPtuHuNCcUJ/8FETleobgXjnV9U43mr9MaDcjDCoAuxZjWZ9vY9KvgH1UU2IJ9dDtopoHCDH0xtuwJZ4L3FGMT0Epq4sn9aSaslAkzz8SEdWIvu2gus6iq36b/yJMjwa/yE2L1zScxmYyyX+EWaHllWqg4uEfAWKmcFXKeSG8rjPgsjW/iJtqymIXkfrqjnX1U5iS67+oGt7y65XuHIX8OVQvT6RlvQrrHoxcoJxlxdvFVU+M8cifKymEWZpvzs1y6gkRhdv8vGpO84SSTS+RGg9hCTWveRzvhZa9aW8M5rS3WAy789A0EhF4C1bKdaJ5GAs1/46b7wnU0U=}
