travis:
  secure:
    BINSTAR_TOKEN: xhwHGvrkcLkgFAbgenOL4mnq9l/yAM5wUjELa3KYwh5UwnwjJmRdpZQYT/3AWPybVUlI6tB8lFPYo/2e7KhLGuuFQUAregq5Mz2rrB5JjMscecJqUCofbwOkrHxkAKg++vKMm6NG4dZmu1X91nIh5BthjrR+2ZSyTKV1NAmtin3FB7Io4I/kwr67lW1Z8Rb8ZFDhYOmKNEARwIRi+ROBhCMyLpNnp8mZXljXL3/RZXrpbDnPGa5fJDN/w/PHprWHcQgp4nzrs9Fw+PboEkewU7HPF+xnGjlRzJji7OH+Zde4XIiDcPaorTKWm3rHnl4QPkUNyCduOMyOyX1cuJzf9VdGV2Eayf4tYVRXVimsWPoHI4jc+tqvtwnxJAqxVsWn66h+cmXgGeXu7P+DdDRYtKdzGxNNcfLHbJfWroAW/D3nRlqN2/W1vUfyK+NI6+tP236RskRmXkSPADUL8bpCM5eMtBY86otNx+W4XZWkT3ZHniPFyPcgiLN5Hd3SuxE3Vx0EtbQ/KfQdNsUmwpzSNch3vxmaysK/N99y14jFVC1XlUSfZBJjIsResTo5os0xKXekxzcLqcar/l+7HXMfVHsReSY8ETX4Rru8OvWANT3tVF8VxgT48lHehwGiYFJpQ/KQUYTbPNJS33VIxdZW/Zk4wufBRU68s8T3TbuZaYA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
